baseURL: https://prof-naru.pages.dev/
# Uncomment below to use aafu as hugo theme. See instructions in README.md
# theme: aafu
languageCode: en-us
build:
  writeStats: true
  enablePostCSS: true
  postcss:
    config: "postcss.config.js"
    options:
      parser: postcss-scss
      map: true
      sourceMap: true
params:
  title: なるみき-Profile-
  author: narumiki
  description: Website title
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Cloudflare](https://www.cloudflare.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "なるみき/さぽにん"
    #tagline: Title
    location: icon:ありおじさん
    photo: profile.png
  social:
    title: Links
    list:
      - icon: fab fa-twitter
        url: "https://x.com/saponin9000"
        title: Twitter
      - icon: fas fa-external-link-alt
        url: "https://live-theater.net/@narumiki"
        title: LTN
      - icon: fab fa-bluesky 
        url: "https://bsky.app/profile/saponin9000.bsky.social"
        title: Bluesky
      - icon: fab fa-twitter
        url: "https://x.com/narumiki_765"
        title: Twitter
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    #- item: education
    - item: publication
    #- item: project
    #- item: skill
    - item: hobby
  aboutme:
    title: 自己紹介
    icon: fas fa-user
    description: ミリアニ先行上映第2幕からの新人プロデューサーです。よろしくお願いします！
  experience:
    title: ミリシタ・ゲームID等
    icon: far fa-address-card
    list:
      - position: ID・名刺
        dates: 2023/9/20 - *なるみき 8RLKRF8Q* ![名刺](images/ml_meishi.jpg)
        details: |1-
          - 同僚追加お気軽にどうぞ！
      - position: イベント実績(一部)
        details: |2-
          - 2023/10/18 - 10/25 · 解夏傀儡 [1771位]
          - 2023/12/16 - 12/24 · ＃年末上々★はぴやばギャルPARTY↑↑～ [1506位]
          - 2024/2/1 - 2/28 · バトンタッチ [1012位]
          - 2024/3/18 - 3/26 · SunRiser [350位]
          - 2024/4/30 - 5/7 · REFRAIN REL@TION [359位]
          - 2024/6/30 - 7/12 · 7D@ys Smile!! [5499位]
            - 春日未来 [634位]
            - 伊吹翼 [618位]
            - ロコ [638位]
            - 北上麗花 [698位]
          - 2024/8/31 - 9/8 · わたしは花、あなたは太陽 [359位]
          - 2024/11/30 - 12/7 · ギブミーメタファー [1297位]
          - 2025/5/31 - 6/7 · U・N・M・E・Iライブ[2167位]
          - 2025/6/29 - 7/12 超々∞MUGEND@I![6304位]
            - 春日未来 [399位]
            - ロコ [486位]
            - 北上麗花 [434位]
  # education:
  #   title: Education
  #   icon: fas fa-graduation-cap
  #   list:
  #     - degree: Ph.D. in Subject
  #       college: University of State-City
  #       dates: 2013 - 2018
  #       thesis_title: "Effect of humans on other humans: a study of human behavior."
  #       thesis_url: "#"
  #     - degree: M.S. in Subject
  #       college: University of State-City
  #       dates: 2013 - 2018
  #       thesis_title: "Effect of humans on other humans: a study of human behavior."
  #       thesis_url: "#"
  #     - degree: B.S. in Subject
  #       college: University of State-City
  #       dates: 2004 - 2009
  publication:
    title: 参加したライブ・イベント
    icon: fas fa-book
    format:
      - date
      - title
      - Venue
      - at
    types:
      - ライブ
      - ライブ(2024年)
      - ライブ(2025年)
      - イベント
      - イベント(2024年)
      - イベント(2025年)
    list:
      - title: >-
          THE IDOLM@STER 765 MILLIONSTARS HOTCHPOTCH FESTIV@L!! 2
        date: "2025/3/29・3/30"
        Venue: "さいたまスーパーアリーナ"
        url: "https://idolmaster-official.jp/live_event/hpf2/"
        at: 両日参加
        type: ライブ(2025年)
      - title: >-
          リスアニ！LIVE 2025 ナツヤスミ
        date: "2025/7/13"
        Venue: "パシフィコ横浜 国立大ホール"
        url: "https://www.lisani.jp/live-special/"
        at: "SUNDAY STAGE参加"
        type: ライブ(2025年)
      - title: >-
          THE IDOLM@STER 20th anniversary ORCHESTRA CONCERT SYMPHONY OF BRILLIANT STARS
        date: "2025/7/21"
        Venue: "パシフィコ横浜 国立大ホール"
        url: "https://idolmaster-official.jp/live_event/orchestra_concert_2025/#news_20250116"
        at: "昼公演配信・夜公演現地参加"
        type: ライブ(2025年)
      - title: >-
          THE IDOLM@STER 765PRO ALLSTARS LIVE ～NEVER END IDOL!!!!!!!!!!!!!～
        date: "2025/8/2・8/3"
        Venue: "Kアリーナ横浜"
        url: "https://idolmaster-official.jp/live_event/765_never_end_idol/"
        at: "両日参加"
        type: ライブ(2025年)
      - title: >-
          THE IDOLM@STER MILLION LIVE! 12thLIVE DAY1 ありのままに。/DAY2 Let’s Sing!
        date: "2025/10/11・10/12"
        Venue: "京王アリーナTOKYO(武蔵野の森スポーツプラザ)"
        url: "https://idolmaster-official.jp/live_event/million12th/"
        at: "両日参加"
        type: ライブ(2025年)
      - title: >-
          THE IDOLM@STER M@STERS OF IDOL WORLD 2025
        date: "2025/12/13・12/14"
        Venue: "京セラドーム大阪"
        url: "https://idolmaster-official.jp/live_event/idolworld2025/"
        at: "両日参加"
        type: ライブ(2025年)
      - title: >-
          如月千早武道館単独公演「OathONE」
        date: "2026/1/24・1/25"
        Venue: "日本武道館"
        url: "https://idolmaster-official.jp/live_event/oath_one/"
        at: "両日参加"
        type: ライブ

      # - title: >-
      #     THE IDOLM@STER MILLION LIVE! 11thLIVE DAY1 Atelier ROCOMOTION!!/DAY2 百合咲き誇るレムリア
      #   date: "2026/3/14・3/15"
      #   Venue: "西日本メッセ(西日本総合展示場)新館"
      #   url: "https://idolmaster-official.jp/live_event/million11th/"
      #   at: "両日参加"
      #   type: ライブ
      # - title: >-
      #     THE IDOLM@STER MILLION LIVE! 13thLIVE DAY1 ???/DAY2 ???
      #     date: "2026/5/5・5/6"
      #     Venue: "有明アリーナ"
      #     url: "https://idolmaster-official.jp/live_event/million13th/"
      #     at: "両日参加"
      #     type: ライブ
      - title: >-
          THE IDOLM@STER MILLION LIVE! 10thLIVE TOUR Act-4 MILLION THE@TER!!!! 
        date: "2024/2/24・2/25"
        Venue: "Kアリーナ横浜"
        url: "https://idolmaster-official.jp/live_event/million10th/information/act4.php"
        type: ライブ(2024年)
        at: 両日参加
      - title: >-
          M@STER EXPO LIVE SHOWCASE
        date: "2024/12/15"
        Venue: "幕張メッセ 国際展示場 展示ホール 3"
        url: "https://idolmaster-official.jp/live_event/master_expo/area/live.php"
        type: ライブ(2024年)
        at: MILLION STAGE 観覧
      - title: >-
          THE IDOLM@STER MILLION RADIO! SPECIAL PARTY 06
        date: "2025/6/15"
        Venue: "立川ステージガーデン"
        type: イベント(2025年)
        at: 昼の部・夜の部
      - title: >-
          THE IDOLM@STER 20th anniversary special party アイ MUST GO ON!! これからもアイマスですよ！20th特別生配信
        date: "2025/7/26"
        Venue: "森のホール21(松戸市文化会館)大ホール"
        url: "https://idolmaster-official.jp/live_event/20th_anniversary_event/"
        type: イベント(2025年)
        at: 現地観覧参加
      - title: >-
          THE IDOLM@STER MOVEMENT STARDOM ROAD THE@TER 07-10 購入者限定リリースイベント
        date: "2025/8/31"
        Venue: "都内某所"
        type: イベント(2025年)
        at: 夜の部
      - title: >-
          THE IDOLM@STER MILLION C@STING 01 解夏傀儡 & 02 エンダーエンダー購入者限定合同朗読イベント
        date: "2024/5/5"
        Venue: "都内某所"
        type: イベント(2024年)
        at: 夜の部
      - title: >-
          THE IDOLM@STER MILLION RADIO! SPECIAL PARTY 05
        date: "2024/5/12"
        Venue: "森のホール21(松戸市文化会館)大ホール"
        type: イベント(2024年)
        at: 昼の部・夜の部
      - title: >-
          アイドルマスターミリオンライブ！展 〜Crossing Our MILLION LIKE!〜
        date: "2024/8/23～8/25"
        Venue: "横浜産貿ホール マリネリア"
        url: "https://idolmaster-official.jp/live_events/millionlike_1"
        type: イベント(2024年)
        at: 全日
      - title: >-
          THE IDOLM@STER MILLION C@STING 03 ミステイク・マーダー！＆04 銀のテーブル木苺ジャム 購入者限定合同朗読イベント
        date: "2024/9/22"
        Venue: 関東某所
        type: イベント(2024年)
        at: 昼の部・夜の部
      - title: >-
          THE IDOLM@STER M@STER EXPO
        date: "2024/12/14・12/15"
        Venue: "幕張メッセ 国際展示場 展示ホール 1～2"
        url: "https://idolmaster-official.jp/live_event/master_expo/"
        type: イベント(2024年)
        at: 全日
  # project:
  #   title: Projects
  #   icon: fas fa-project-diagram
  #   list:
  #     - title: Project 1
  #       url: "#"
  #       description: Description of the project
  #     - title: Project 2
  #       url: "#"
  #       description: Description of the project
  #     - title: Project 3
  #       url: "#"
  #       description: Description of the project
  #     - title: Project 4
  #       url: "#"
  #       description: Description of the project
  # skill:
  #   title: Skills
  #   panelId: skill-panel
  #   icon: fas fa-cogs
  #   list:
  #     - skill: "Skill 1, Skill 2"
  #       skillrating: 90
  #     - skill: Skill 3
  #       skillrating: 80
  #     - skill: Skill 4
  #       skillrating: 50
  hobby:
    title: その他趣味
    icon: fas fa-gamepad
    list:
      - hobby: 写真撮影(夕焼け・電柱・人物等 LUMIX G100D)
      - hobby: 散歩
      - hobby: 読書
      - hobby: ポルノグラフィティ(LoveUp!会員 2024/9/8～)
